---
- import_playbook: ../common-packer/provision/baseline.yaml

- hosts: all
  become_user: root
  become_method: sudo

  tasks:
    - name: 'Install Canonical Snapcraft'
      command: apt-get install -y snapcraft
      become: true


