---

- project:
    name: core-config-watcher
    project-name: core-config-watcher
    project: core-config-watcher
    mvn-settings: core-config-watcher-settings
    archive-artifacts: ''
    cron: 'H 11 * * *'
    stream:
      - 'master':
          branch: 'master'
      - 'california':
          branch: 'california'
      - 'delhi':
          branch: 'delhi'

    jobs:
      - '{project-name}-github-maven-jobs'
