---

- project:
    name: core-config-watcher
    project-name: core-config-watcher
    project: core-config-watcher
    mvn-settings: core-config-watcher-settings
    archive-artifacts: ''
    cron: 'H 11 * * *'
    stream:
      - 'master':
          branch: 'master'
      - 'barcelona':
          branch: 'barcelona'
      - 'california':
          branch: 'california'
    jobs:
      - '{project-name}-{stream}-verify-java'
      - '{project-name}-{stream}-merge-java'
      - '{project-name}-github-maven-jobs'
